title: CANFAR
tagline: Processing and Storage on the cloud
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
site_env: demo
env:
    demo:
        cadc: 'demo.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'demo.canfar.net'
        apps: 'demo.canfar.net'
    rc:
        cadc: 'rc.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'rc.canfar.net'
        apps: 'rcapps.canfar.net'
    prod:
        cadc: 'www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'www.canfar.net'
        apps: 'apps.canfar.net'
baseurl: ''
future: true
github_url: 'https://github.com/canfar/canfar.github.io'
twitter_url: 'https://twitter.com/astro_canfar'
slack_url: '/slack'
repository: 'canfar/canfar.github.io'
exclude:
    - node_modules
