name: CANFAR
tagline: Processing and Storage on the cloud
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
future: true
github:
  repository_url: 'https://github.com/canfar/beta-canfar.github.io'

# For beta site only!
# baseurl: '/beta-canfar.github.io'
