title: CANFAR
tagline: Processing and Storage on the cloud
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
site_env: vm
env:
    demo:
        cadc: 'http://demo.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'http://demo.canfar.net'
        apps: 'http://demo.canfar.net'
    rc:
        cadc: 'http://rc.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'http://rc.canfar.net'
        apps: 'http://rcapps.canfar.net'
    prod:
        cadc: 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: 'http://www.canfar.net'
        apps: 'http://apps.canfar.net'
    docker:
        cadc: 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'
        canfar: ''
        apps: ''
    vm:
        cadc: 'http://jeevesh.cadc.dao.nrc.ca'
        canfar: 'http://jeevesh.cadc.dao.nrc.ca'
        apps: 'http://jeevesh.cadc.dao.nrc.ca'
baseurl: ''
future: true
github_url: 'https://github.com/canfar/canfar.github.io'
twitter_url: 'https://twitter.com/astro_canfar'
slack_url: '/slack'
repository: 'canfar/canfar.github.io'
exclude:
    - node_modules
