name: CANFAR
tagline: Processing and Storage on the cloud
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
future: true
github_url: 'https://github.com/canfar/canfar.github.io'
repository: 'canfar/canfar.github.io'
