version: '3.2'
services:
  canfar:
    hostname: ${HOSTNAME}
    image: canfar/canfar-site
    command: bash -c "bundle install && bundle exec jekyll s --host ${HOSTNAME}"
    ports:
      - 4000:4000
    volumes:
      - './:/srv/jekyll'
    networks:
      - canfar

networks:
  canfar:
