version: '3.2'
services:
  canfar:
    hostname: ${HOSTNAME:-localhost}
    build: ./
    image: canfar/canfar-site
    build: .
    command: bash -c "bundle install && bundle exec jekyll s --incremental --host ${HOSTNAME}"
    ports:
      - 4000:4000
    volumes:
      - './:/srv/jekyll'
    networks:
      - canfar

networks:
  canfar:
